version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres2:
    image: postgres:16
    container_name: postgres-db-2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myappdb2
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata2:
